export const ShopList = [
    {
        DisplayName: "Lock&Lock Official Store (Cửa hàng chính hãng)",
        Place: "Quận 7, TP. Hồ Chí Minh",
        Image: "77bc0a1ee72fd0576c9f9a8cf45ff48d",
        Description: "",
        RatingStar: 5,
        FollowerCount: 10000,
        ItemCount: 30,
        ResponseRate: 22,
        ResponseTime: 3939,
        IsShopeeVerified: false,
        IsOfficialShop: true,
        ShopName: "locknlockvn",
    },
    {
        DisplayName: "Lock&Lock Official Store (Cửa hàng chính hãng)",
        Place: "Quận 7, TP. Hồ Chí Minh",
        Image: "77bc0a1ee72fd0576c9f9a8cf45ff48d",
        Description: "",
        RatingStar: 5,
        FollowerCount: 10000,
        ItemCount: 30,
        ResponseRate: 22,
        ResponseTime: 3939,
        IsShopeeVerified: false,
        IsOfficialShop: true,
        ShopName: "locknlockvn",
    },
    {
        DisplayName: "Lock&Lock Official Store (Cửa hàng chính hãng)",
        Place: "Quận 7, TP. Hồ Chí Minh",
        Image: "77bc0a1ee72fd0576c9f9a8cf45ff48d",
        Description: "",
        RatingStar: 5,
        FollowerCount: 10000,
        ItemCount: 30,
        ResponseRate: 22,
        ResponseTime: 3939,
        IsShopeeVerified: false,
        IsOfficialShop: true,
        ShopName: "locknlockvn",
    }
]