name: cd

on:
  push:
    branches:
      - release

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Get current time
        uses: 1466587594/get-current-time@v1
        id: current-time
        with:
          format: DD-M-YYYY-HH-MM-SS
          utcOffset: "+07:00"

      - name: Build && Push to Dockerhub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: daongocthanh/gr-frontend:${{ steps.current-time.outputs.formattedTime }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare deploy antifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.yml"
          target: "gr2"
          overwrite: 1

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export IMAGE_TAG=${{ steps.current-time.outputs.formattedTime }}
            docker stack deploy -c /root/sociallistening/backend-deployment.yaml sociallistening
